spring.application.name=mate

# PostgreSQL (Supabase)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME:Postgres}
spring.datasource.password=${DB_PASSWORD:RPWezMym4VQX7000}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.task.scheduling.pool.size=5

jwt.secret=${JWT_SECRET}
jwt.expire-ms=${JWT_EXPIRE_MS:86400000}

spring.profiles.active=${SPRING_PROFILES_ACTIVE:prod}