spring.application.name=mate

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.data-source-properties.prepareThreshold=0

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

spring.task.scheduling.pool.size=5

jwt.secret=${JWT_SECRET}
jwt.expire-ms=${JWT_EXPIRE_MS:86400000}

logging.level.root=INFO
logging.level.com.oliveyoung.mate=DEBUG

spring.profiles.active=${SPRING_PROFILES_ACTIVE:prod}
